name: Update SISS HTML Source

on:
  schedule:
    - cron: "0 2 * * 1"  # Lunes a las 02:00 UTC
  workflow_dispatch:

jobs:
  download_siss_source:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Download SISS HTML Source
        run: python scripts/download_siss_source.py

      - name: Commit if changed
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add html/tariff_siss_source.html
          git diff --cached --quiet || git commit -m "Update SISS HTML source"
          git push
