name: Parse SISS PDFs

on:
  schedule:
    - cron: "0 3 * * 1"  # Todos los lunes a las 03:00 UTC
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  parse_tarifas_pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pymupdf requests

      - name: Parse SISS PDFs
        run: python scripts/parse_tariffs_pdfs.py

      - name: Commit parsed data if changed
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add json/tarifas_siss_data.json
          git diff --cached --quiet || git commit -m "Update parsed SISS tarifas data"
          git push
