name: Scrapper

on:
  schedule:
    - cron: '0 3 * * *'  # Todos los días a las 03:00 UTC (00:00 Chile)
  workflow_dispatch:      # Permite ejecución manual

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necesario para hacer commit

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scripts/scraper.py

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add data/ page_hash.txt last_modified.txt
            git commit -m "🗂️ Update tarifas SISS - $(date -u +"%Y-%m-%d %H:%M:%S")"
            git push
          else
            echo "No changes to commit"
          fi
