name: SISS Tarifas Scraper

on:
  schedule:
    - cron: '0 4 * * *'  # Ejecutar todos los días a las 04:00 UTC
  workflow_dispatch:

jobs:
  scrape_and_parse:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 PyMuPDF

      - name: Run scraping and parsing script
        run: |
          python scraper.py

      - name: Check for changes
        id: git-check
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/ || true
          git diff --cached --quiet || echo "::set-output name=changed::true"

      - name: Commit and push if changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git commit -m "chore: update scraped tarifas data"
          git push
